"""Dodanie id_club do Competition

Revision ID: 05cca7a92b0f
Revises: 5666739f5cc8
Create Date: 2025-02-04 00:53:33.772401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05cca7a92b0f'
down_revision = '5666739f5cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_club', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_competition_club', 'club', ['id_club'], ['id_club'])  # ✅ Dodano nazwę constraint

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition', schema=None) as batch_op:
        batch_op.drop_constraint('fk_competition_club', type_='foreignkey')  # ✅ Usunięcie constraint z nazwą
        batch_op.drop_column('id_club')

    # ### end Alembic commands ###
