"""Initial migration

Revision ID: 5666739f5cc8
Revises: 
Create Date: 2025-01-29 15:00:33.366520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5666739f5cc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id_club', sa.Integer(), nullable=False),
    sa.Column('club_name', sa.String(length=120), nullable=False),
    sa.Column('club_city', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_club')
    )
    op.create_table('competition',
    sa.Column('id_competition', sa.Integer(), nullable=False),
    sa.Column('competition_name', sa.String(length=120), nullable=False),
    sa.Column('competition_city', sa.String(length=120), nullable=False),
    sa.Column('competition_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_competition')
    )
    op.create_table('role',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_role'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('swimming_style',
    sa.Column('id_style', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('style_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_style')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.Enum('K', 'M', name='gender_enum'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('email_address', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id_club'], ),
    sa.ForeignKeyConstraint(['id_role'], ['role.id_role'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('result',
    sa.Column('id_result', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_club', sa.Integer(), nullable=False),
    sa.Column('id_competition', sa.Integer(), nullable=False),
    sa.Column('id_style', sa.Integer(), nullable=False),
    sa.Column('distance_time', sa.Float(), nullable=False),
    sa.Column('reaction_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_club'], ['club.id_club'], ),
    sa.ForeignKeyConstraint(['id_competition'], ['competition.id_competition'], ),
    sa.ForeignKeyConstraint(['id_style'], ['swimming_style.id_style'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_result')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('user')
    op.drop_table('swimming_style')
    op.drop_table('role')
    op.drop_table('competition')
    op.drop_table('club')
    # ### end Alembic commands ###
